### ISSUE TITLE
java.lang.NoClassDefFoundError: de/mrapp/util/Condition

### ISSUE THREAD

**Issue by wesleyderoode** [michael-rapp/Apriori#10]
It seems that the Condition class is missing. I cannot find it in the jar file or your repository either.

**Comment by michael-rapp** [comment]
It's included in the library's dependency "JavaUtil" (see https://github.com/michael-rapp/JavaUtil).

**Comment by wesleyderoode** [comment]
Thanks for your fast response, i got it working now.
